server {
    listen 80;
    listen [::]:80;
    server_name desk.zyrotechbd.com;
    return 301 https://desk.zyrotechbd.com$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name desk.zyrotechbd.com;

    ssl_certificate     /etc/letsencrypt/live/wildcard-zyrotechbd/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/wildcard-zyrotechbd/privkey.pem;

    root /var/www/zyro_isp_support/panel/public;
    index index.php;
    client_max_body_size 20m;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    }

    location ~ /\.(?!well-known) { deny all; }
}
